"""
Seed the AgentCart database with demo merchant, products, and commerce policy.

Usage:
    python seed.py
"""
import sys
import os

# Ensure the backend directory is on the path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from app.database import engine, SessionLocal, Base
from app.models.merchant import Merchant
from app.models.product import Product
from app.models.policy import CommercePolicy


MERCHANT_ID = "merchant-demo-001"

PRODUCTS = [
    {
        "id": "lenovo-loq-15",
        "sku": "LAP-001",
        "name": "Lenovo LOQ 15",
        "description": "15.6-inch powerhouse for coding and gaming. Features a high-performance Ryzen 7 processor, dedicated RTX 4050 graphics, and a vibrant 15.6-inch display. (AgentCart Demo Configuration)",
        "category": "laptop",
        "price": 64999,
        "currency": "INR",
        "inventory": 12,
        "attributes": {
            "ram": "16GB",
            "storage": "512GB SSD",
            "gpu": "RTX 4050",
            "processor": "Ryzen 7",
            "display": "15.6 inch",
        },
        "image_url": "https://lh3.googleusercontent.com/aida-public/AB6AXuANxibGnRSuO191yXH9KuvHTQckEIdwvtnCj7Ht0OwXLvs98xwSmSGV4GrudmgeRQUwjXCGv0Dcriqm82G3AtcB93yaGwrnbqOprsg13o8sRThRhUYxI-iYNKxauwm5MkZZEa7etqCSY5oRKuBIuqNzpNR9keVBOYPCVwxA0ImGc6I2rWTozkbrCshem7JrgaMP-XO5qcTK3-vrP4P9z9WccUeptDeX9Efs6gXzBPWHAtzuE4lsE8mO",
        "hero_image_url": "https://lh3.googleusercontent.com/aida-public/AB6AXuBIGkySwKIHKJfjkoZDIhqixJzreSC-72-3ib_OPH0r5CVAy_t4XXMd9HTin7jH6NWXV4TmiE3VVGJFG0lyfisOwzl2FuuiXIlo_2iwSRL2re3DxOSFNHSFakn2Sqq7uXDV0rPZ7aYMbsOIOKlpecydWSciJBm_NUId4vXWJ7eOrW3qXOv7GDCLVy_45Mswhub9pzzSmfj3VtLJQnl3i5iK_lS_M7qyvCajZ9OL8_cveqeezUChsBkO",
    },
    {
        "id": "ideapad-slim-5",
        "sku": "LAP-002",
        "name": "Lenovo IdeaPad Slim 5",
        "description": "Better CPU, but integrated graphics. Less ideal for gaming. Premium build with exceptional keyboard and trackpad for long coding sessions. (AgentCart Demo Configuration)",
        "category": "laptop",
        "price": 68500,
        "currency": "INR",
        "inventory": 8,
        "attributes": {
            "ram": "16GB",
            "storage": "512GB SSD",
            "gpu": "Iris Xe",
            "processor": "Intel Core i7",
            "display": "14 inch",
        },
        "image_url": "",
        "hero_image_url": "",
    },
    {
        "id": "acer-nitro-v15",
        "sku": "LAP-003",
        "name": "Acer Nitro V 15",
        "description": "RTX 4060, but only 8GB RAM. Might struggle with heavy coding. Excellent for gaming with high refresh rate display. (AgentCart Demo Configuration)",
        "category": "laptop",
        "price": 69990,
        "currency": "INR",
        "inventory": 5,
        "attributes": {
            "ram": "8GB",
            "storage": "512GB SSD",
            "gpu": "RTX 4060",
            "processor": "Intel Core i5",
            "display": "15.6 inch",
        },
        "image_url": "",
        "hero_image_url": "",
    },
    {
        "id": "wireless-mouse",
        "sku": "ACC-001",
        "name": "Wireless Mouse",
        "description": "Ergonomic wireless mouse with Bluetooth 5.0 connectivity, silent clicks, and long battery life.",
        "category": "accessory",
        "price": 1499,
        "currency": "INR",
        "inventory": 45,
        "attributes": {
            "connectivity": "Bluetooth 5.0",
            "battery": "18 months",
            "dpi": "4000",
        },
        "image_url": "",
        "hero_image_url": "",
    },
    {
        "id": "mechanical-keyboard",
        "sku": "ACC-002",
        "name": "Mechanical Keyboard",
        "description": "Full-size mechanical keyboard with hot-swappable switches, RGB backlighting, and USB-C connection.",
        "category": "accessory",
        "price": 3499,
        "currency": "INR",
        "inventory": 30,
        "attributes": {
            "switch_type": "Mechanical (Red)",
            "layout": "Full-size",
            "backlight": "RGB",
            "connectivity": "USB-C",
        },
        "image_url": "",
        "hero_image_url": "",
    },
    {
        "id": "laptop-stand",
        "sku": "ACC-003",
        "name": "Laptop Stand",
        "description": "Adjustable aluminum laptop stand with ergonomic height settings and cable management.",
        "category": "accessory",
        "price": 2499,
        "currency": "INR",
        "inventory": 25,
        "attributes": {
            "material": "Aluminum",
            "adjustable": "Yes",
            "max_laptop_size": "17 inch",
        },
        "image_url": "",
        "hero_image_url": "",
    },
    {
        "id": "usb-c-hub",
        "sku": "ACC-004",
        "name": "USB-C Hub Pro",
        "description": "7-in-1 USB-C hub with HDMI 4K, USB 3.0, SD card reader, and 100W power delivery passthrough.",
        "category": "accessory",
        "price": 3999,
        "currency": "INR",
        "inventory": 20,
        "attributes": {
            "ports": "7-in-1",
            "hdmi": "4K@60Hz",
            "power_delivery": "100W",
        },
        "image_url": "",
        "hero_image_url": "",
    },
    {
        "id": "noise-cancelling-headphones",
        "sku": "AUD-001",
        "name": "Noise Cancelling Headphones",
        "description": "Over-ear wireless headphones with active noise cancellation, 30-hour battery, and premium comfort.",
        "category": "audio",
        "price": 7999,
        "currency": "INR",
        "inventory": 15,
        "attributes": {
            "type": "Over-ear",
            "anc": "Active Noise Cancellation",
            "battery": "30 hours",
            "connectivity": "Bluetooth 5.2",
        },
        "image_url": "",
        "hero_image_url": "",
    },
    {
        "id": "webcam-hd",
        "sku": "ACC-005",
        "name": "HD Webcam Pro",
        "description": "1080p webcam with auto-focus, built-in microphone, and privacy shutter for remote work.",
        "category": "accessory",
        "price": 4999,
        "currency": "INR",
        "inventory": 18,
        "attributes": {
            "resolution": "1080p",
            "fps": "60",
            "autofocus": "Yes",
            "microphone": "Built-in dual mic",
        },
        "image_url": "",
        "hero_image_url": "",
    },
    {
        "id": "monitor-27",
        "sku": "MON-001",
        "name": "UltraWide Monitor 27\"",
        "description": "27-inch QHD IPS monitor with 165Hz refresh rate, HDR400, and USB-C input for seamless laptop connectivity.",
        "category": "monitor",
        "price": 24999,
        "currency": "INR",
        "inventory": 7,
        "attributes": {
            "size": "27 inch",
            "resolution": "2560x1440 QHD",
            "refresh_rate": "165Hz",
            "panel": "IPS",
            "hdr": "HDR400",
        },
        "image_url": "",
        "hero_image_url": "",
    },
    {
        "id": "rgb-gaming-mousepad",
        "sku": "ACC-006",
        "name": "RGB Gaming Mousepad",
        "description": "Extended RGB mousepad with 14 lighting modes, micro-textured surface, and non-slip rubber base.",
        "category": "accessory",
        "price": 1299,
        "currency": "INR",
        "inventory": 50,
        "attributes": {
            "size": "800x300mm",
            "lighting": "14 RGB modes",
            "surface": "Micro-textured cloth",
        },
        "image_url": "",
        "hero_image_url": "",
    },
    {
        "id": "portable-ssd-1tb",
        "sku": "STR-001",
        "name": "Portable SSD 1TB",
        "description": "Compact portable SSD with 1050MB/s read speed, USB 3.2 Gen 2, and shock-resistant design.",
        "category": "storage",
        "price": 5999,
        "currency": "INR",
        "inventory": 22,
        "attributes": {
            "capacity": "1TB",
            "read_speed": "1050 MB/s",
            "interface": "USB 3.2 Gen 2",
            "form_factor": "Portable",
        },
        "image_url": "",
        "hero_image_url": "",
    },

    # ============================================================
    # CATALOG EXPANSION — added to broaden AgentCart from a laptop
    # storefront into a general merchant catalog. See conversation
    # for the approved category distribution. All images below are
    # local, deterministic, category-level placeholders — no
    # external hotlinks, nothing that misrepresents the product.
    # ============================================================

    # ─── Laptops (12 new — total 15) ──────────────────────────────
    {
        "id": "dell-xps-13",
        "sku": "LAP-004",
        "name": "Dell XPS 13",
        "description": "Ultra-portable 13-inch flagship ultrabook with a InfinityEdge display, machined aluminum chassis, and all-day battery life.",
        "category": "laptop",
        "price": 94990,
        "currency": "INR",
        "inventory": 9,
        "attributes": {
            "ram": "16GB", "storage": "512GB SSD", "gpu": "Intel Iris Xe",
            "processor": "Intel Core i7-1355U", "display": "13.4 inch FHD+",
            "weight": "1.2kg", "battery_life": "12 hours",
        },
        "image_url": "/products/placeholders/laptop.svg",
        "hero_image_url": "/products/placeholders/laptop.svg",
    },
    {
        "id": "dell-inspiron-15",
        "sku": "LAP-005",
        "name": "Dell Inspiron 15",
        "description": "Reliable everyday laptop for students, with a spacious 15.6-inch display and all-day usability for classwork and browsing.",
        "category": "laptop",
        "price": 42990,
        "currency": "INR",
        "inventory": 20,
        "attributes": {
            "ram": "8GB", "storage": "512GB SSD", "gpu": "Intel UHD Graphics",
            "processor": "Intel Core i3-1215U", "display": "15.6 inch FHD",
            "weight": "1.65kg", "battery_life": "8 hours",
        },
        "image_url": "/products/placeholders/laptop.svg",
        "hero_image_url": "/products/placeholders/laptop.svg",
    },
    {
        "id": "hp-pavilion-15",
        "sku": "LAP-006",
        "name": "HP Pavilion 15",
        "description": "Balanced student laptop with a crisp FHD display, comfortable keyboard, and enough power for coursework and light multitasking.",
        "category": "laptop",
        "price": 54990,
        "currency": "INR",
        "inventory": 15,
        "attributes": {
            "ram": "8GB", "storage": "512GB SSD", "gpu": "Intel Iris Xe",
            "processor": "Intel Core i5-1235U", "display": "15.6 inch FHD",
            "weight": "1.75kg", "battery_life": "9 hours",
        },
        "image_url": "/products/placeholders/laptop.svg",
        "hero_image_url": "/products/placeholders/laptop.svg",
    },
    {
        "id": "hp-victus-16",
        "sku": "LAP-007",
        "name": "HP Victus 16",
        "description": "Value gaming laptop with a dedicated RTX 4050 and a 144Hz display, built for competitive titles without a flagship price tag.",
        "category": "laptop",
        "price": 74990,
        "currency": "INR",
        "inventory": 10,
        "attributes": {
            "ram": "16GB", "storage": "512GB SSD", "gpu": "RTX 4050",
            "processor": "Ryzen 5 7640HS", "display": "16.1 inch FHD 144Hz",
            "weight": "2.29kg", "battery_life": "6 hours",
        },
        "image_url": "/products/placeholders/laptop.svg",
        "hero_image_url": "/products/placeholders/laptop.svg",
    },
    {
        "id": "asus-rog-strix-g16",
        "sku": "LAP-008",
        "name": "Asus ROG Strix G16",
        "description": "High-refresh QHD gaming laptop with an RTX 4060 and a high-core-count i7, tuned for AAA titles at high settings.",
        "category": "laptop",
        "price": 129990,
        "currency": "INR",
        "inventory": 5,
        "attributes": {
            "ram": "16GB", "storage": "1TB SSD", "gpu": "RTX 4060",
            "processor": "Intel Core i7-13650HX", "display": "16 inch QHD 165Hz",
            "weight": "2.5kg", "battery_life": "5 hours",
        },
        "image_url": "/products/placeholders/laptop.svg",
        "hero_image_url": "/products/placeholders/laptop.svg",
    },
    {
        "id": "asus-vivobook-15",
        "sku": "LAP-009",
        "name": "Asus Vivobook 15",
        "description": "Budget-friendly 15.6-inch laptop for students who need a light, dependable machine for browsing, docs, and streaming.",
        "category": "laptop",
        "price": 38990,
        "currency": "INR",
        "inventory": 25,
        "attributes": {
            "ram": "8GB", "storage": "512GB SSD", "gpu": "Integrated",
            "processor": "Intel Core i3-1315U", "display": "15.6 inch FHD",
            "weight": "1.7kg", "battery_life": "8 hours",
        },
        "image_url": "/products/placeholders/laptop.svg",
        "hero_image_url": "/products/placeholders/laptop.svg",
    },
    {
        "id": "apple-macbook-air-m2",
        "sku": "LAP-010",
        "name": "Apple MacBook Air M2",
        "description": "Fanless, ultra-light creator laptop built around Apple's M2 chip, with an 18-hour battery and a stunning Liquid Retina display.",
        "category": "laptop",
        "price": 114900,
        "currency": "INR",
        "inventory": 8,
        "attributes": {
            "ram": "8GB", "storage": "256GB SSD", "gpu": "8-core GPU",
            "processor": "Apple M2", "display": "13.6 inch Liquid Retina",
            "weight": "1.24kg", "battery_life": "18 hours",
        },
        "image_url": "/products/placeholders/laptop.svg",
        "hero_image_url": "/products/placeholders/laptop.svg",
    },
    {
        "id": "apple-macbook-pro-14",
        "sku": "LAP-011",
        "name": "Apple MacBook Pro 14",
        "description": "Pro-grade creator laptop with the M3 Pro chip and a Liquid Retina XDR display, built for video editing and heavy multitasking.",
        "category": "laptop",
        "price": 169900,
        "currency": "INR",
        "inventory": 4,
        "attributes": {
            "ram": "18GB", "storage": "512GB SSD", "gpu": "14-core GPU",
            "processor": "Apple M3 Pro", "display": "14.2 inch Liquid Retina XDR",
            "weight": "1.55kg", "battery_life": "17 hours",
        },
        "image_url": "/products/placeholders/laptop.svg",
        "hero_image_url": "/products/placeholders/laptop.svg",
    },
    {
        "id": "dell-xps-15",
        "sku": "LAP-012",
        "name": "Dell XPS 15",
        "description": "Creator-focused laptop pairing a 3.5K OLED display with an RTX 4050, suited to photo/video editing and light 3D work.",
        "category": "laptop",
        "price": 154990,
        "currency": "INR",
        "inventory": 6,
        "attributes": {
            "ram": "16GB", "storage": "1TB SSD", "gpu": "RTX 4050",
            "processor": "Intel Core i7-13700H", "display": "15.6 inch OLED 3.5K",
            "weight": "1.86kg", "battery_life": "10 hours",
        },
        "image_url": "/products/placeholders/laptop.svg",
        "hero_image_url": "/products/placeholders/laptop.svg",
    },
    {
        "id": "hp-elitebook-840",
        "sku": "LAP-013",
        "name": "HP EliteBook 840",
        "description": "Business-grade laptop with enterprise security features, a light magnesium chassis, and reliable all-day battery life.",
        "category": "laptop",
        "price": 89990,
        "currency": "INR",
        "inventory": 12,
        "attributes": {
            "ram": "16GB", "storage": "512GB SSD", "gpu": "Intel Iris Xe",
            "processor": "Intel Core i5-1335U", "display": "14 inch FHD",
            "weight": "1.36kg", "battery_life": "11 hours",
        },
        "image_url": "/products/placeholders/laptop.svg",
        "hero_image_url": "/products/placeholders/laptop.svg",
    },
    {
        "id": "lenovo-thinkpad-x1-carbon",
        "sku": "LAP-014",
        "name": "Lenovo ThinkPad X1 Carbon",
        "description": "Premium business ultrabook with a legendary keyboard, carbon-fiber chassis, and MIL-SPEC durability for road warriors.",
        "category": "laptop",
        "price": 149990,
        "currency": "INR",
        "inventory": 5,
        "attributes": {
            "ram": "16GB", "storage": "1TB SSD", "gpu": "Intel Iris Xe",
            "processor": "Intel Core i7-1355U", "display": "14 inch WUXGA",
            "weight": "1.12kg", "battery_life": "15 hours",
        },
        "image_url": "/products/placeholders/laptop.svg",
        "hero_image_url": "/products/placeholders/laptop.svg",
    },
    {
        "id": "msi-katana-15",
        "sku": "LAP-015",
        "name": "MSI Katana 15",
        "description": "Value-focused gaming laptop with an RTX 4050 and a 144Hz panel — strong 1080p gaming performance at a competitive price.",
        "category": "laptop",
        "price": 79990,
        "currency": "INR",
        "inventory": 9,
        "attributes": {
            "ram": "16GB", "storage": "512GB SSD", "gpu": "RTX 4050",
            "processor": "Intel Core i7-13620H", "display": "15.6 inch FHD 144Hz",
            "weight": "2.25kg", "battery_life": "6 hours",
        },
        "image_url": "/products/placeholders/laptop.svg",
        "hero_image_url": "/products/placeholders/laptop.svg",
    },

    # ─── Smartphones (14 new) ──────────────────────────────────────
    {
        "id": "apple-iphone-15",
        "sku": "PHN-001",
        "name": "Apple iPhone 15",
        "description": "Apple's mainstream flagship with a 48MP main camera, Dynamic Island, and the A16 Bionic chip in a durable aluminum-and-glass body.",
        "category": "smartphone",
        "price": 79900,
        "currency": "INR",
        "inventory": 18,
        "attributes": {
            "ram": "6GB", "storage": "128GB", "display": "6.1 inch Super Retina XDR",
            "camera": "48MP Dual", "battery": "3349mAh", "chipset": "A16 Bionic", "5g": "Yes",
        },
        "image_url": "/products/placeholders/smartphone.svg",
        "hero_image_url": "/products/placeholders/smartphone.svg",
    },
    {
        "id": "apple-iphone-15-pro",
        "sku": "PHN-002",
        "name": "Apple iPhone 15 Pro",
        "description": "Titanium-bodied pro flagship with a 5x telephoto camera, A17 Pro chip, and ProRAW/ProRes video capture.",
        "category": "smartphone",
        "price": 134900,
        "currency": "INR",
        "inventory": 8,
        "attributes": {
            "ram": "8GB", "storage": "256GB", "display": "6.1 inch Super Retina XDR ProMotion",
            "camera": "48MP Triple, 5x zoom", "battery": "3274mAh", "chipset": "A17 Pro", "5g": "Yes",
        },
        "image_url": "/products/placeholders/smartphone.svg",
        "hero_image_url": "/products/placeholders/smartphone.svg",
    },
    {
        "id": "samsung-galaxy-s24",
        "sku": "PHN-003",
        "name": "Samsung Galaxy S24",
        "description": "Compact Android flagship with a bright 120Hz AMOLED display and Galaxy AI features for everyday photography and productivity.",
        "category": "smartphone",
        "price": 74999,
        "currency": "INR",
        "inventory": 14,
        "attributes": {
            "ram": "8GB", "storage": "256GB", "display": "6.2 inch Dynamic AMOLED 2X",
            "camera": "50MP Triple", "battery": "4000mAh", "chipset": "Exynos 2400", "5g": "Yes",
        },
        "image_url": "/products/placeholders/smartphone.svg",
        "hero_image_url": "/products/placeholders/smartphone.svg",
    },
    {
        "id": "samsung-galaxy-s24-ultra",
        "sku": "PHN-004",
        "name": "Samsung Galaxy S24 Ultra",
        "description": "Samsung's camera-first flagship with a 200MP sensor, 10x optical zoom, S Pen support, and a titanium frame.",
        "category": "smartphone",
        "price": 129999,
        "currency": "INR",
        "inventory": 6,
        "attributes": {
            "ram": "12GB", "storage": "256GB", "display": "6.8 inch Dynamic AMOLED 2X",
            "camera": "200MP Quad, 10x zoom", "battery": "5000mAh", "chipset": "Snapdragon 8 Gen 3", "5g": "Yes",
        },
        "image_url": "/products/placeholders/smartphone.svg",
        "hero_image_url": "/products/placeholders/smartphone.svg",
    },
    {
        "id": "samsung-galaxy-a55",
        "sku": "PHN-005",
        "name": "Samsung Galaxy A55",
        "description": "Mid-range all-rounder with a 120Hz AMOLED display, solid battery life, and a capable triple-camera setup.",
        "category": "smartphone",
        "price": 38999,
        "currency": "INR",
        "inventory": 22,
        "attributes": {
            "ram": "8GB", "storage": "128GB", "display": "6.6 inch Super AMOLED 120Hz",
            "camera": "50MP Triple", "battery": "5000mAh", "chipset": "Exynos 1480", "5g": "Yes",
        },
        "image_url": "/products/placeholders/smartphone.svg",
        "hero_image_url": "/products/placeholders/smartphone.svg",
    },
    {
        "id": "samsung-galaxy-m14",
        "sku": "PHN-006",
        "name": "Samsung Galaxy M14",
        "description": "Budget-friendly Samsung phone with a massive 6000mAh battery, ideal for buyers who prioritize battery life over flash.",
        "category": "smartphone",
        "price": 13999,
        "currency": "INR",
        "inventory": 35,
        "attributes": {
            "ram": "4GB", "storage": "64GB", "display": "6.6 inch PLS LCD 90Hz",
            "camera": "50MP Triple", "battery": "6000mAh", "chipset": "Exynos 1330", "5g": "Yes",
        },
        "image_url": "/products/placeholders/smartphone.svg",
        "hero_image_url": "/products/placeholders/smartphone.svg",
    },
    {
        "id": "oneplus-12",
        "sku": "PHN-007",
        "name": "OnePlus 12",
        "description": "Performance flagship with Snapdragon 8 Gen 3, 100W fast charging, and a Hasselblad-tuned triple camera system.",
        "category": "smartphone",
        "price": 64999,
        "currency": "INR",
        "inventory": 12,
        "attributes": {
            "ram": "12GB", "storage": "256GB", "display": "6.82 inch AMOLED 120Hz",
            "camera": "50MP Triple Hasselblad", "battery": "5400mAh", "chipset": "Snapdragon 8 Gen 3", "5g": "Yes",
        },
        "image_url": "/products/placeholders/smartphone.svg",
        "hero_image_url": "/products/placeholders/smartphone.svg",
    },
    {
        "id": "oneplus-nord-ce4",
        "sku": "PHN-008",
        "name": "OnePlus Nord CE4",
        "description": "Mid-range phone with fast charging and a smooth 120Hz display, aimed at buyers who want flagship feel on a budget.",
        "category": "smartphone",
        "price": 24999,
        "currency": "INR",
        "inventory": 28,
        "attributes": {
            "ram": "8GB", "storage": "128GB", "display": "6.7 inch AMOLED 120Hz",
            "camera": "50MP Dual", "battery": "5500mAh", "chipset": "Snapdragon 7 Gen 3", "5g": "Yes",
        },
        "image_url": "/products/placeholders/smartphone.svg",
        "hero_image_url": "/products/placeholders/smartphone.svg",
    },
    {
        "id": "xiaomi-redmi-note-13-pro",
        "sku": "PHN-009",
        "name": "Xiaomi Redmi Note 13 Pro",
        "description": "Budget camera-focused phone with a 200MP OIS main sensor — unusually strong photography for the price bracket.",
        "category": "smartphone",
        "price": 26999,
        "currency": "INR",
        "inventory": 30,
        "attributes": {
            "ram": "8GB", "storage": "256GB", "display": "6.67 inch AMOLED 120Hz",
            "camera": "200MP OIS", "battery": "5100mAh", "chipset": "Snapdragon 7s Gen 2", "5g": "Yes",
        },
        "image_url": "/products/placeholders/smartphone.svg",
        "hero_image_url": "/products/placeholders/smartphone.svg",
    },
    {
        "id": "xiaomi-14",
        "sku": "PHN-010",
        "name": "Xiaomi 14",
        "description": "Compact flagship with a Leica-tuned triple camera and Snapdragon 8 Gen 3, built for buyers who want flagship power in a smaller body.",
        "category": "smartphone",
        "price": 69999,
        "currency": "INR",
        "inventory": 9,
        "attributes": {
            "ram": "12GB", "storage": "256GB", "display": "6.36 inch AMOLED 120Hz",
            "camera": "50MP Triple Leica", "battery": "4610mAh", "chipset": "Snapdragon 8 Gen 3", "5g": "Yes",
        },
        "image_url": "/products/placeholders/smartphone.svg",
        "hero_image_url": "/products/placeholders/smartphone.svg",
    },
    {
        "id": "google-pixel-8",
        "sku": "PHN-011",
        "name": "Google Pixel 8",
        "description": "Computational-photography flagship with Google Tensor G3, known for class-leading AI photo and video processing.",
        "category": "smartphone",
        "price": 64999,
        "currency": "INR",
        "inventory": 10,
        "attributes": {
            "ram": "8GB", "storage": "128GB", "display": "6.2 inch OLED 120Hz",
            "camera": "50MP Dual with AI", "battery": "4575mAh", "chipset": "Google Tensor G3", "5g": "Yes",
        },
        "image_url": "/products/placeholders/smartphone.svg",
        "hero_image_url": "/products/placeholders/smartphone.svg",
    },
    {
        "id": "google-pixel-8a",
        "sku": "PHN-012",
        "name": "Google Pixel 8a",
        "description": "Mid-range Pixel with the flagship Tensor G3 chip and Google's computational camera pipeline at a more accessible price.",
        "category": "smartphone",
        "price": 52999,
        "currency": "INR",
        "inventory": 16,
        "attributes": {
            "ram": "8GB", "storage": "128GB", "display": "6.1 inch OLED 120Hz",
            "camera": "64MP Dual", "battery": "4492mAh", "chipset": "Google Tensor G3", "5g": "Yes",
        },
        "image_url": "/products/placeholders/smartphone.svg",
        "hero_image_url": "/products/placeholders/smartphone.svg",
    },
    {
        "id": "vivo-v30",
        "sku": "PHN-013",
        "name": "Vivo V30",
        "description": "Camera-centric mid-ranger with portrait studio lighting effects, tuned for flattering selfies and portraits.",
        "category": "smartphone",
        "price": 33999,
        "currency": "INR",
        "inventory": 20,
        "attributes": {
            "ram": "8GB", "storage": "128GB", "display": "6.78 inch AMOLED 120Hz",
            "camera": "50MP Dual, portrait lighting", "battery": "5000mAh", "chipset": "Snapdragon 7 Gen 3", "5g": "Yes",
        },
        "image_url": "/products/placeholders/smartphone.svg",
        "hero_image_url": "/products/placeholders/smartphone.svg",
    },
    {
        "id": "realme-narzo-70",
        "sku": "PHN-014",
        "name": "Realme Narzo 70",
        "description": "Budget smartphone with a smooth 120Hz display and a capable AI-assisted 50MP camera for entry-level buyers.",
        "category": "smartphone",
        "price": 15999,
        "currency": "INR",
        "inventory": 32,
        "attributes": {
            "ram": "6GB", "storage": "128GB", "display": "6.72 inch IPS LCD 120Hz",
            "camera": "50MP AI Dual", "battery": "5000mAh", "chipset": "Dimensity 6300", "5g": "Yes",
        },
        "image_url": "/products/placeholders/smartphone.svg",
        "hero_image_url": "/products/placeholders/smartphone.svg",
    },

    # ─── Headphones / Earbuds (11 new — total 12) ──────────────────
    {
        "id": "sony-wh-1000xm5",
        "sku": "AUD-002",
        "name": "Sony WH-1000XM5",
        "description": "Industry-benchmark active noise cancellation with 30-hour battery life — the default pick for frequent flyers.",
        "category": "audio",
        "price": 29990,
        "currency": "INR",
        "inventory": 12,
        "attributes": {
            "type": "Over-ear", "anc": "Industry-leading ANC", "battery": "30 hours",
            "connectivity": "Bluetooth 5.2", "mic_quality": "Premium 4-mic", "use_case": "Travel & Commute",
        },
        "image_url": "/products/placeholders/audio.svg",
        "hero_image_url": "/products/placeholders/audio.svg",
    },
    {
        "id": "bose-quietcomfort-earbuds-ii",
        "sku": "AUD-003",
        "name": "Bose QuietComfort Earbuds II",
        "description": "Compact ANC earbuds with Bose's CustomTune personalized noise cancellation and a secure, comfortable fit.",
        "category": "audio",
        "price": 24990,
        "currency": "INR",
        "inventory": 10,
        "attributes": {
            "type": "In-ear TWS", "anc": "Adaptive ANC", "battery": "6 hrs (24 with case)",
            "connectivity": "Bluetooth 5.3", "mic_quality": "Dual-mic", "use_case": "Travel & Calls",
        },
        "image_url": "/products/placeholders/audio.svg",
        "hero_image_url": "/products/placeholders/audio.svg",
    },
    {
        "id": "apple-airpods-pro-2",
        "sku": "AUD-004",
        "name": "Apple AirPods Pro (2nd Gen)",
        "description": "Apple's flagship earbuds with adaptive ANC, Transparency mode, and seamless integration across the Apple ecosystem.",
        "category": "audio",
        "price": 24900,
        "currency": "INR",
        "inventory": 20,
        "attributes": {
            "type": "In-ear TWS", "anc": "Active Noise Cancellation", "battery": "6 hrs (30 with case)",
            "connectivity": "Bluetooth 5.3", "mic_quality": "Dual beamforming mic", "use_case": "Everyday & Calls",
        },
        "image_url": "/products/placeholders/audio.svg",
        "hero_image_url": "/products/placeholders/audio.svg",
    },
    {
        "id": "samsung-galaxy-buds-2-pro",
        "sku": "AUD-005",
        "name": "Samsung Galaxy Buds2 Pro",
        "description": "Compact ANC earbuds with high-fidelity 24-bit audio, tuned for pairing with Samsung Galaxy phones.",
        "category": "audio",
        "price": 17999,
        "currency": "INR",
        "inventory": 18,
        "attributes": {
            "type": "In-ear TWS", "anc": "Intelligent ANC", "battery": "5 hrs (18 with case)",
            "connectivity": "Bluetooth 5.3", "mic_quality": "Dual-mic", "use_case": "Everyday & Calls",
        },
        "image_url": "/products/placeholders/audio.svg",
        "hero_image_url": "/products/placeholders/audio.svg",
    },
    {
        "id": "jbl-tune-770nc",
        "sku": "AUD-006",
        "name": "JBL Tune 770NC",
        "description": "Budget-friendly ANC over-ear headphones with a 44-hour battery — noise cancellation without the flagship price.",
        "category": "audio",
        "price": 6999,
        "currency": "INR",
        "inventory": 26,
        "attributes": {
            "type": "Over-ear", "anc": "Active Noise Cancellation", "battery": "44 hours",
            "connectivity": "Bluetooth 5.3", "mic_quality": "Standard", "use_case": "Travel & Commute",
        },
        "image_url": "/products/placeholders/audio.svg",
        "hero_image_url": "/products/placeholders/audio.svg",
    },
    {
        "id": "boat-airdopes-141",
        "sku": "AUD-007",
        "name": "boAt Airdopes 141",
        "description": "Entry-level true wireless earbuds with a 42-hour total playback case — an affordable everyday pick.",
        "category": "audio",
        "price": 1299,
        "currency": "INR",
        "inventory": 60,
        "attributes": {
            "type": "In-ear TWS", "anc": "No", "battery": "6 hrs (42 with case)",
            "connectivity": "Bluetooth 5.3", "mic_quality": "Standard", "use_case": "Everyday",
        },
        "image_url": "/products/placeholders/audio.svg",
        "hero_image_url": "/products/placeholders/audio.svg",
    },
    {
        "id": "sennheiser-momentum-4",
        "sku": "AUD-008",
        "name": "Sennheiser Momentum 4",
        "description": "Audiophile-grade over-ear headphones with adaptive ANC and an exceptional 60-hour battery life.",
        "category": "audio",
        "price": 27990,
        "currency": "INR",
        "inventory": 7,
        "attributes": {
            "type": "Over-ear", "anc": "Adaptive ANC", "battery": "60 hours",
            "connectivity": "Bluetooth 5.2", "mic_quality": "Premium 4-mic", "use_case": "Travel & Studio",
        },
        "image_url": "/products/placeholders/audio.svg",
        "hero_image_url": "/products/placeholders/audio.svg",
    },
    {
        "id": "jbl-endurance-run-2",
        "sku": "AUD-009",
        "name": "JBL Endurance Run 2",
        "description": "Sweat-resistant wired in-ear headphones designed for the gym, with a secure hook-style fit.",
        "category": "audio",
        "price": 999,
        "currency": "INR",
        "inventory": 40,
        "attributes": {
            "type": "In-ear wired", "anc": "No", "battery": "N/A (wired)",
            "connectivity": "3.5mm", "mic_quality": "In-line mic", "use_case": "Sport & Gym",
        },
        "image_url": "/products/placeholders/audio.svg",
        "hero_image_url": "/products/placeholders/audio.svg",
    },
    {
        "id": "boat-rockerz-450",
        "sku": "AUD-010",
        "name": "boAt Rockerz 450",
        "description": "Affordable wireless over-ear headphones with 15-hour battery life for everyday listening.",
        "category": "audio",
        "price": 1499,
        "currency": "INR",
        "inventory": 45,
        "attributes": {
            "type": "Over-ear", "anc": "No", "battery": "15 hours",
            "connectivity": "Bluetooth 5.0", "mic_quality": "Standard", "use_case": "Everyday",
        },
        "image_url": "/products/placeholders/audio.svg",
        "hero_image_url": "/products/placeholders/audio.svg",
    },
    {
        "id": "razer-kraken-x",
        "sku": "AUD-011",
        "name": "Razer Kraken X",
        "description": "Lightweight wired gaming headset with a cardioid boom mic, tuned for accurate positional audio.",
        "category": "audio",
        "price": 4499,
        "currency": "INR",
        "inventory": 20,
        "attributes": {
            "type": "Over-ear gaming", "anc": "No", "battery": "N/A (wired)",
            "connectivity": "3.5mm", "mic_quality": "Cardioid boom mic", "use_case": "Gaming",
        },
        "image_url": "/products/placeholders/audio.svg",
        "hero_image_url": "/products/placeholders/audio.svg",
    },
    {
        "id": "hyperx-cloud-2",
        "sku": "AUD-012",
        "name": "HyperX Cloud II",
        "description": "Best-selling gaming headset with virtual 7.1 surround sound and a detachable noise-cancelling mic.",
        "category": "audio",
        "price": 7999,
        "currency": "INR",
        "inventory": 15,
        "attributes": {
            "type": "Over-ear gaming", "anc": "No", "battery": "N/A (wired USB)",
            "connectivity": "USB / 3.5mm", "mic_quality": "Detachable noise-cancelling mic", "use_case": "Gaming",
        },
        "image_url": "/products/placeholders/audio.svg",
        "hero_image_url": "/products/placeholders/audio.svg",
    },

    # ─── Monitors (7 new — total 8) ─────────────────────────────────
    {
        "id": "lg-ultragear-27gp850",
        "sku": "MON-002",
        "name": "LG UltraGear 27GP850",
        "description": "27-inch Nano IPS gaming monitor with 165Hz refresh rate and HDR10 — built for competitive and story-driven titles alike.",
        "category": "monitor",
        "price": 32990,
        "currency": "INR",
        "inventory": 8,
        "attributes": {
            "size": "27 inch", "resolution": "2560x1440 QHD", "refresh_rate": "165Hz",
            "panel": "Nano IPS", "hdr": "HDR10", "ports": "HDMI 2.1, DisplayPort",
        },
        "image_url": "/products/placeholders/monitor.svg",
        "hero_image_url": "/products/placeholders/monitor.svg",
    },
    {
        "id": "samsung-odyssey-g5",
        "sku": "MON-003",
        "name": "Samsung Odyssey G5",
        "description": "Curved QHD gaming monitor with a 144Hz refresh rate, designed for immersive, wraparound gameplay.",
        "category": "monitor",
        "price": 21999,
        "currency": "INR",
        "inventory": 10,
        "attributes": {
            "size": "27 inch", "resolution": "2560x1440 QHD", "refresh_rate": "144Hz",
            "panel": "VA Curved", "hdr": "HDR10", "ports": "HDMI, DisplayPort",
        },
        "image_url": "/products/placeholders/monitor.svg",
        "hero_image_url": "/products/placeholders/monitor.svg",
    },
    {
        "id": "dell-s2721qs",
        "sku": "MON-004",
        "name": "Dell S2721QS",
        "description": "27-inch 4K IPS monitor with accurate color reproduction — a strong pick for productivity and light creative work.",
        "category": "monitor",
        "price": 28999,
        "currency": "INR",
        "inventory": 9,
        "attributes": {
            "size": "27 inch", "resolution": "3840x2160 4K", "refresh_rate": "60Hz",
            "panel": "IPS", "hdr": "HDR400", "ports": "HDMI, DisplayPort",
        },
        "image_url": "/products/placeholders/monitor.svg",
        "hero_image_url": "/products/placeholders/monitor.svg",
    },
    {
        "id": "benq-gw2480",
        "sku": "MON-005",
        "name": "BenQ GW2480",
        "description": "Budget-friendly office monitor with eye-care flicker-free technology, ideal for long work sessions.",
        "category": "monitor",
        "price": 8499,
        "currency": "INR",
        "inventory": 20,
        "attributes": {
            "size": "23.8 inch", "resolution": "1920x1080 FHD", "refresh_rate": "60Hz",
            "panel": "IPS", "hdr": "No", "ports": "HDMI, VGA",
        },
        "image_url": "/products/placeholders/monitor.svg",
        "hero_image_url": "/products/placeholders/monitor.svg",
    },
    {
        "id": "asus-tuf-vg249q",
        "sku": "MON-006",
        "name": "Asus TUF VG249Q",
        "description": "Affordable 144Hz gaming monitor with FreeSync support — a popular entry point into high-refresh gaming.",
        "category": "monitor",
        "price": 14999,
        "currency": "INR",
        "inventory": 15,
        "attributes": {
            "size": "23.8 inch", "resolution": "1920x1080 FHD", "refresh_rate": "144Hz",
            "panel": "IPS", "hdr": "No", "ports": "HDMI, DisplayPort",
        },
        "image_url": "/products/placeholders/monitor.svg",
        "hero_image_url": "/products/placeholders/monitor.svg",
    },
    {
        "id": "lg-34wn80c-ultrawide",
        "sku": "MON-007",
        "name": "LG 34WN80C UltraWide",
        "description": "34-inch curved ultrawide monitor for productivity — enough screen real estate to replace a dual-monitor setup.",
        "category": "monitor",
        "price": 36990,
        "currency": "INR",
        "inventory": 6,
        "attributes": {
            "size": "34 inch", "resolution": "3440x1440 UWQHD", "refresh_rate": "60Hz",
            "panel": "IPS Curved", "hdr": "HDR10", "ports": "USB-C, HDMI, DisplayPort",
        },
        "image_url": "/products/placeholders/monitor.svg",
        "hero_image_url": "/products/placeholders/monitor.svg",
    },
    {
        "id": "samsung-viewfinity-s8-4k",
        "sku": "MON-008",
        "name": "Samsung ViewFinity S8",
        "description": "32-inch 4K monitor with 90W USB-C power delivery — charges a laptop and drives a 4K display over a single cable.",
        "category": "monitor",
        "price": 47999,
        "currency": "INR",
        "inventory": 5,
        "attributes": {
            "size": "32 inch", "resolution": "3840x2160 4K", "refresh_rate": "60Hz",
            "panel": "IPS", "hdr": "HDR400", "ports": "USB-C 90W, HDMI, DisplayPort",
        },
        "image_url": "/products/placeholders/monitor.svg",
        "hero_image_url": "/products/placeholders/monitor.svg",
    },

    # ─── Accessories: keyboards / mice / webcams (8 new) ───────────
    {
        "id": "logitech-mx-master-3s",
        "sku": "ACC-007",
        "name": "Logitech MX Master 3S",
        "description": "Premium ergonomic mouse with an 8000 DPI sensor and quiet clicks — a favorite among professionals.",
        "category": "accessory",
        "price": 9995,
        "currency": "INR",
        "inventory": 18,
        "attributes": {
            "type": "Ergonomic Mouse", "connectivity": "Bluetooth / USB Receiver",
            "dpi": "8000", "battery": "70 days",
        },
        "image_url": "/products/placeholders/accessory.svg",
        "hero_image_url": "/products/placeholders/accessory.svg",
    },
    {
        "id": "logitech-g502-hero",
        "sku": "ACC-008",
        "name": "Logitech G502 Hero",
        "description": "Wired gaming mouse with an ultra-precise 25,600 DPI sensor and customizable weight tuning.",
        "category": "accessory",
        "price": 3995,
        "currency": "INR",
        "inventory": 25,
        "attributes": {
            "type": "Gaming Mouse", "connectivity": "Wired USB",
            "dpi": "25600", "battery": "N/A (wired)",
        },
        "image_url": "/products/placeholders/accessory.svg",
        "hero_image_url": "/products/placeholders/accessory.svg",
    },
    {
        "id": "razer-deathadder-v3",
        "sku": "ACC-009",
        "name": "Razer DeathAdder V3",
        "description": "Wireless esports mouse with a 30,000 DPI sensor and a 90-hour battery, built for competitive accuracy.",
        "category": "accessory",
        "price": 6499,
        "currency": "INR",
        "inventory": 20,
        "attributes": {
            "type": "Gaming Mouse", "connectivity": "Wireless 2.4GHz",
            "dpi": "30000", "battery": "90 hours",
        },
        "image_url": "/products/placeholders/accessory.svg",
        "hero_image_url": "/products/placeholders/accessory.svg",
    },
    {
        "id": "logitech-mx-keys",
        "sku": "ACC-010",
        "name": "Logitech MX Keys",
        "description": "Premium wireless keyboard with backlit keys that adjust to ambient light, tuned for fast, quiet typing.",
        "category": "accessory",
        "price": 9495,
        "currency": "INR",
        "inventory": 15,
        "attributes": {
            "switch_type": "Scissor", "layout": "Full-size",
            "backlight": "White backlit", "connectivity": "Bluetooth / USB-C",
        },
        "image_url": "/products/placeholders/accessory.svg",
        "hero_image_url": "/products/placeholders/accessory.svg",
    },
    {
        "id": "razer-huntsman-mini",
        "sku": "ACC-011",
        "name": "Razer Huntsman Mini",
        "description": "Compact 60% mechanical keyboard with optical switches for near-instant actuation — built for desk space and speed.",
        "category": "accessory",
        "price": 9999,
        "currency": "INR",
        "inventory": 10,
        "attributes": {
            "switch_type": "Optical (Red)", "layout": "60%",
            "backlight": "RGB", "connectivity": "USB-C",
        },
        "image_url": "/products/placeholders/accessory.svg",
        "hero_image_url": "/products/placeholders/accessory.svg",
    },
    {
        "id": "logitech-k380",
        "sku": "ACC-012",
        "name": "Logitech K380",
        "description": "Compact multi-device wireless keyboard that pairs with up to three devices and switches between them instantly.",
        "category": "accessory",
        "price": 2995,
        "currency": "INR",
        "inventory": 30,
        "attributes": {
            "switch_type": "Scissor", "layout": "Compact",
            "backlight": "No", "connectivity": "Bluetooth (multi-device)",
        },
        "image_url": "/products/placeholders/accessory.svg",
        "hero_image_url": "/products/placeholders/accessory.svg",
    },
    {
        "id": "logitech-c920",
        "sku": "ACC-013",
        "name": "Logitech C920 HD Pro",
        "description": "The long-standing standard for reliable 1080p webcams, with smooth autofocus and a built-in stereo mic.",
        "category": "accessory",
        "price": 6495,
        "currency": "INR",
        "inventory": 22,
        "attributes": {
            "resolution": "1080p", "fps": "30", "autofocus": "Yes",
            "microphone": "Stereo built-in",
        },
        "image_url": "/products/placeholders/accessory.svg",
        "hero_image_url": "/products/placeholders/accessory.svg",
    },
    {
        "id": "logitech-brio-4k",
        "sku": "ACC-014",
        "name": "Logitech Brio 4K",
        "description": "Premium 4K webcam with HDR and Windows Hello support, tuned for professional streaming and video calls.",
        "category": "accessory",
        "price": 15995,
        "currency": "INR",
        "inventory": 8,
        "attributes": {
            "resolution": "4K", "fps": "30", "autofocus": "Yes",
            "microphone": "Dual stereo with noise reduction",
        },
        "image_url": "/products/placeholders/accessory.svg",
        "hero_image_url": "/products/placeholders/accessory.svg",
    },

    # ─── Accessories: bags / travel / lifestyle (9 new) ────────────
    {
        "id": "american-tourister-laptop-backpack",
        "sku": "ACC-015",
        "name": "American Tourister Laptop Backpack",
        "description": "Durable 25L daily backpack with a padded laptop compartment and water-resistant polyester shell.",
        "category": "accessory",
        "price": 1899,
        "currency": "INR",
        "inventory": 35,
        "attributes": {
            "capacity": "25L", "material": "Polyester",
            "laptop_size": "Up to 15.6 inch", "water_resistant": "Yes",
        },
        "image_url": "/products/placeholders/accessory.svg",
        "hero_image_url": "/products/placeholders/accessory.svg",
    },
    {
        "id": "skybags-footloose-backpack",
        "sku": "ACC-016",
        "name": "Skybags Footloose Groove Backpack",
        "description": "Spacious 30L backpack with multiple organizer compartments, built for daily commutes and short trips.",
        "category": "accessory",
        "price": 1399,
        "currency": "INR",
        "inventory": 40,
        "attributes": {
            "capacity": "30L", "material": "Polyester",
            "laptop_size": "Up to 15.6 inch", "water_resistant": "Yes",
        },
        "image_url": "/products/placeholders/accessory.svg",
        "hero_image_url": "/products/placeholders/accessory.svg",
    },
    {
        "id": "wildcraft-travel-duffel",
        "sku": "ACC-017",
        "name": "Wildcraft Travel Duffel Bag",
        "description": "45L ripstop duffel bag built for weekend trips, with reinforced handles and a detachable shoulder strap.",
        "category": "accessory",
        "price": 1799,
        "currency": "INR",
        "inventory": 22,
        "attributes": {
            "capacity": "45L", "material": "Ripstop Nylon",
            "laptop_size": "N/A", "water_resistant": "Yes",
        },
        "image_url": "/products/placeholders/accessory.svg",
        "hero_image_url": "/products/placeholders/accessory.svg",
    },
    {
        "id": "anker-737-power-bank",
        "sku": "ACC-018",
        "name": "Anker 737 Power Bank",
        "description": "High-capacity 24,000mAh power bank with 140W USB-C Power Delivery — fast enough to charge a laptop.",
        "category": "accessory",
        "price": 8999,
        "currency": "INR",
        "inventory": 18,
        "attributes": {
            "capacity": "24000mAh", "output": "140W USB-C PD", "ports": "2x USB-C, 1x USB-A",
        },
        "image_url": "/products/placeholders/accessory.svg",
        "hero_image_url": "/products/placeholders/accessory.svg",
    },
    {
        "id": "mi-power-bank-3i-20000mah",
        "sku": "ACC-019",
        "name": "Mi Power Bank 3i",
        "description": "Reliable 20,000mAh power bank with dual-input charging and triple-output ports for everyday travel.",
        "category": "accessory",
        "price": 1699,
        "currency": "INR",
        "inventory": 40,
        "attributes": {
            "capacity": "20000mAh", "output": "18W fast charge", "ports": "2x USB-A, 1x USB-C",
        },
        "image_url": "/products/placeholders/accessory.svg",
        "hero_image_url": "/products/placeholders/accessory.svg",
    },
    {
        "id": "spigen-laptop-sleeve-15",
        "sku": "ACC-020",
        "name": "Spigen Laptop Sleeve 15-inch",
        "description": "Slim neoprene sleeve with a soft interior lining, protecting laptops up to 15 inches from scratches and light bumps.",
        "category": "accessory",
        "price": 1299,
        "currency": "INR",
        "inventory": 30,
        "attributes": {
            "material": "Neoprene", "laptop_size": "Up to 15 inch", "water_resistant": "Yes",
        },
        "image_url": "/products/placeholders/accessory.svg",
        "hero_image_url": "/products/placeholders/accessory.svg",
    },
    {
        "id": "amazonbasics-cable-organizer-pouch",
        "sku": "ACC-021",
        "name": "AmazonBasics Cable Organizer Pouch",
        "description": "Compact travel pouch with elastic loops and mesh pockets to keep cables, chargers, and adapters tangle-free.",
        "category": "accessory",
        "price": 499,
        "currency": "INR",
        "inventory": 55,
        "attributes": {
            "capacity": "Small", "material": "Polyester", "water_resistant": "No",
        },
        "image_url": "/products/placeholders/accessory.svg",
        "hero_image_url": "/products/placeholders/accessory.svg",
    },
    {
        "id": "ugreen-65w-travel-adapter",
        "sku": "ACC-022",
        "name": "UGREEN 65W Travel Adapter",
        "description": "Compact GaN travel charger with three ports and a universal plug, built to replace a full bag of chargers.",
        "category": "accessory",
        "price": 2499,
        "currency": "INR",
        "inventory": 28,
        "attributes": {
            "output": "65W GaN", "ports": "2x USB-C, 1x USB-A", "compatibility": "Universal plug",
        },
        "image_url": "/products/placeholders/accessory.svg",
        "hero_image_url": "/products/placeholders/accessory.svg",
    },
    {
        "id": "milton-thermosteel-flask",
        "sku": "ACC-023",
        "name": "Milton Thermosteel Flask 1L",
        "description": "Vacuum-insulated stainless steel flask that keeps drinks hot or cold for up to 24 hours — a desk and travel staple.",
        "category": "accessory",
        "price": 899,
        "currency": "INR",
        "inventory": 45,
        "attributes": {
            "capacity": "1L", "material": "Stainless Steel", "insulation": "24 hours hot/cold",
        },
        "image_url": "/products/placeholders/accessory.svg",
        "hero_image_url": "/products/placeholders/accessory.svg",
    },

    # ─── Smartwatches / Fitness (8 new) ─────────────────────────────
    {
        "id": "apple-watch-series-9",
        "sku": "SWT-001",
        "name": "Apple Watch Series 9",
        "description": "Apple's flagship smartwatch with an always-on Retina display, ECG, and deep iOS integration.",
        "category": "smartwatch",
        "price": 41900,
        "currency": "INR",
        "inventory": 10,
        "attributes": {
            "display": "Always-On Retina LTPO OLED", "battery": "18 hours", "gps": "Yes",
            "water_resistance": "50m", "health_sensors": "ECG, SpO2, Heart Rate", "compatibility": "iOS",
        },
        "image_url": "/products/placeholders/smartwatch.svg",
        "hero_image_url": "/products/placeholders/smartwatch.svg",
    },
    {
        "id": "samsung-galaxy-watch-6",
        "sku": "SWT-002",
        "name": "Samsung Galaxy Watch 6",
        "description": "Premium Android smartwatch with a bright Super AMOLED display and comprehensive health tracking.",
        "category": "smartwatch",
        "price": 29999,
        "currency": "INR",
        "inventory": 12,
        "attributes": {
            "display": "Super AMOLED", "battery": "40 hours", "gps": "Yes",
            "water_resistance": "5ATM", "health_sensors": "ECG, SpO2, Heart Rate", "compatibility": "Android",
        },
        "image_url": "/products/placeholders/smartwatch.svg",
        "hero_image_url": "/products/placeholders/smartwatch.svg",
    },
    {
        "id": "noise-colorfit-pro-4",
        "sku": "SWT-003",
        "name": "Noise ColorFit Pro 4",
        "description": "Budget AMOLED smartwatch with a week-long battery and Bluetooth calling, popular as an everyday first smartwatch.",
        "category": "smartwatch",
        "price": 2999,
        "currency": "INR",
        "inventory": 40,
        "attributes": {
            "display": "1.72 inch AMOLED", "battery": "7 days", "gps": "Connected GPS",
            "water_resistance": "IP68", "health_sensors": "SpO2, Heart Rate", "compatibility": "iOS & Android",
        },
        "image_url": "/products/placeholders/smartwatch.svg",
        "hero_image_url": "/products/placeholders/smartwatch.svg",
    },
    {
        "id": "boat-wave-neo",
        "sku": "SWT-004",
        "name": "boAt Wave Neo",
        "description": "Affordable smartwatch with a bright HD display and week-long battery life for casual fitness tracking.",
        "category": "smartwatch",
        "price": 1799,
        "currency": "INR",
        "inventory": 45,
        "attributes": {
            "display": "1.83 inch HD", "battery": "7 days", "gps": "Connected GPS",
            "water_resistance": "IP68", "health_sensors": "SpO2, Heart Rate", "compatibility": "iOS & Android",
        },
        "image_url": "/products/placeholders/smartwatch.svg",
        "hero_image_url": "/products/placeholders/smartwatch.svg",
    },
    {
        "id": "garmin-forerunner-165",
        "sku": "SWT-005",
        "name": "Garmin Forerunner 165",
        "description": "Dedicated GPS running watch with advanced running dynamics and multi-day battery — built for serious runners.",
        "category": "smartwatch",
        "price": 31990,
        "currency": "INR",
        "inventory": 6,
        "attributes": {
            "display": "AMOLED", "battery": "11 days", "gps": "Built-in GPS",
            "water_resistance": "5ATM", "health_sensors": "Running dynamics, SpO2, Heart Rate", "compatibility": "iOS & Android",
        },
        "image_url": "/products/placeholders/smartwatch.svg",
        "hero_image_url": "/products/placeholders/smartwatch.svg",
    },
    {
        "id": "amazfit-gts-4",
        "sku": "SWT-006",
        "name": "Amazfit GTS 4",
        "description": "Slim AMOLED smartwatch with built-in GPS and an 8-day battery, balancing style with fitness tracking.",
        "category": "smartwatch",
        "price": 12999,
        "currency": "INR",
        "inventory": 15,
        "attributes": {
            "display": "AMOLED", "battery": "8 days", "gps": "Built-in GPS",
            "water_resistance": "5ATM", "health_sensors": "SpO2, Heart Rate, Stress", "compatibility": "iOS & Android",
        },
        "image_url": "/products/placeholders/smartwatch.svg",
        "hero_image_url": "/products/placeholders/smartwatch.svg",
    },
    {
        "id": "fitbit-charge-6",
        "sku": "SWT-007",
        "name": "Fitbit Charge 6",
        "description": "Fitness-focused band with built-in GPS, ECG, and Google apps integration for detailed activity and sleep tracking.",
        "category": "smartwatch",
        "price": 14999,
        "currency": "INR",
        "inventory": 14,
        "attributes": {
            "display": "AMOLED", "battery": "7 days", "gps": "Built-in GPS",
            "water_resistance": "50m", "health_sensors": "ECG, SpO2, Heart Rate", "compatibility": "iOS & Android",
        },
        "image_url": "/products/placeholders/smartwatch.svg",
        "hero_image_url": "/products/placeholders/smartwatch.svg",
    },
    {
        "id": "mi-smart-band-8",
        "sku": "SWT-008",
        "name": "Mi Smart Band 8",
        "description": "Ultra-affordable fitness band with a vivid AMOLED display and a class-leading 16-day battery life.",
        "category": "smartwatch",
        "price": 2499,
        "currency": "INR",
        "inventory": 50,
        "attributes": {
            "display": "AMOLED", "battery": "16 days", "gps": "Connected GPS",
            "water_resistance": "5ATM", "health_sensors": "SpO2, Heart Rate", "compatibility": "iOS & Android",
        },
        "image_url": "/products/placeholders/smartwatch.svg",
        "hero_image_url": "/products/placeholders/smartwatch.svg",
    },

    # ─── Cameras (6 new) ─────────────────────────────────────────
    {
        "id": "canon-eos-r50",
        "sku": "CAM-001",
        "name": "Canon EOS R50",
        "description": "Entry-level mirrorless camera with a 24.2MP APS-C sensor and 4K video, well-suited to first-time interchangeable-lens buyers.",
        "category": "camera",
        "price": 68999,
        "currency": "INR",
        "inventory": 6,
        "attributes": {
            "sensor": "24.2MP APS-C", "resolution": "24.2MP", "zoom": "Interchangeable lens",
            "video": "4K30", "stabilization": "Digital IS", "form_factor": "Mirrorless",
        },
        "image_url": "/products/placeholders/camera.svg",
        "hero_image_url": "/products/placeholders/camera.svg",
    },
    {
        "id": "sony-alpha-a6100",
        "sku": "CAM-002",
        "name": "Sony Alpha a6100",
        "description": "Compact mirrorless camera with fast, reliable autofocus — a strong entry point into the Sony E-mount lens ecosystem.",
        "category": "camera",
        "price": 64990,
        "currency": "INR",
        "inventory": 5,
        "attributes": {
            "sensor": "24.2MP APS-C", "resolution": "24.2MP", "zoom": "Interchangeable lens",
            "video": "4K30", "stabilization": "Digital IS", "form_factor": "Mirrorless",
        },
        "image_url": "/products/placeholders/camera.svg",
        "hero_image_url": "/products/placeholders/camera.svg",
    },
    {
        "id": "gopro-hero12-black",
        "sku": "CAM-003",
        "name": "GoPro HERO12 Black",
        "description": "Rugged waterproof action camera with HyperSmooth 6.0 stabilization and 5.3K video, built for extreme sports and travel.",
        "category": "camera",
        "price": 42990,
        "currency": "INR",
        "inventory": 12,
        "attributes": {
            "sensor": "1/1.9 inch", "resolution": "27MP", "zoom": "Digital",
            "video": "5.3K60", "stabilization": "HyperSmooth 6.0", "form_factor": "Action Camera",
        },
        "image_url": "/products/placeholders/camera.svg",
        "hero_image_url": "/products/placeholders/camera.svg",
    },
    {
        "id": "dji-osmo-pocket-3",
        "sku": "CAM-004",
        "name": "DJI Osmo Pocket 3",
        "description": "Pocket-sized 3-axis gimbal camera with a 1-inch sensor, purpose-built for smooth, cinematic vlogging footage.",
        "category": "camera",
        "price": 53990,
        "currency": "INR",
        "inventory": 8,
        "attributes": {
            "sensor": "1 inch", "resolution": "9.4MP", "zoom": "Digital",
            "video": "4K120", "stabilization": "3-axis mechanical gimbal", "form_factor": "Pocket Vlogging Camera",
        },
        "image_url": "/products/placeholders/camera.svg",
        "hero_image_url": "/products/placeholders/camera.svg",
    },
    {
        "id": "insta360-x4",
        "sku": "CAM-005",
        "name": "Insta360 X4",
        "description": "360-degree action camera capturing 8K footage, letting you reframe every shot after recording.",
        "category": "camera",
        "price": 49990,
        "currency": "INR",
        "inventory": 7,
        "attributes": {
            "sensor": "Dual 1/2 inch", "resolution": "72MP photo", "zoom": "Digital",
            "video": "8K30 360", "stabilization": "FlowState", "form_factor": "360 Action Camera",
        },
        "image_url": "/products/placeholders/camera.svg",
        "hero_image_url": "/products/placeholders/camera.svg",
    },
    {
        "id": "canon-powershot-g7x-mark-iii",
        "sku": "CAM-006",
        "name": "Canon PowerShot G7 X Mark III",
        "description": "Pocketable vlogging compact with a 1-inch sensor and a flip-up screen, a long-time favorite among content creators.",
        "category": "camera",
        "price": 56995,
        "currency": "INR",
        "inventory": 6,
        "attributes": {
            "sensor": "1 inch", "resolution": "20.1MP", "zoom": "4.2x Optical",
            "video": "4K30", "stabilization": "Optical IS", "form_factor": "Compact",
        },
        "image_url": "/products/placeholders/camera.svg",
        "hero_image_url": "/products/placeholders/camera.svg",
    },

    # ─── Consoles / Controllers (6 new) ─────────────────────────────
    {
        "id": "sony-playstation-5",
        "sku": "GAM-001",
        "name": "Sony PlayStation 5",
        "description": "Sony's flagship console with an 825GB SSD and ray-tracing support, built around the DualSense controller's haptics.",
        "category": "gaming",
        "price": 54990,
        "currency": "INR",
        "inventory": 6,
        "attributes": {
            "storage": "825GB SSD", "platform": "PS5", "connectivity": "Wi-Fi 6, Bluetooth 5.1",
            "compatibility": "PS5 & select PS4 titles",
        },
        "image_url": "/products/placeholders/gaming.svg",
        "hero_image_url": "/products/placeholders/gaming.svg",
    },
    {
        "id": "microsoft-xbox-series-x",
        "sku": "GAM-002",
        "name": "Microsoft Xbox Series X",
        "description": "Microsoft's most powerful console with a 1TB SSD and full backward compatibility across Xbox generations.",
        "category": "gaming",
        "price": 52990,
        "currency": "INR",
        "inventory": 5,
        "attributes": {
            "storage": "1TB SSD", "platform": "Xbox", "connectivity": "Wi-Fi, Bluetooth",
            "compatibility": "Xbox Series & backward compatible",
        },
        "image_url": "/products/placeholders/gaming.svg",
        "hero_image_url": "/products/placeholders/gaming.svg",
    },
    {
        "id": "nintendo-switch-oled",
        "sku": "GAM-003",
        "name": "Nintendo Switch OLED",
        "description": "Hybrid handheld/console with a vivid 7-inch OLED screen, playable docked on a TV or on the go.",
        "category": "gaming",
        "price": 34999,
        "currency": "INR",
        "inventory": 10,
        "attributes": {
            "storage": "64GB", "platform": "Nintendo Switch", "connectivity": "Wi-Fi, Bluetooth",
            "compatibility": "Nintendo Switch titles",
        },
        "image_url": "/products/placeholders/gaming.svg",
        "hero_image_url": "/products/placeholders/gaming.svg",
    },
    {
        "id": "sony-dualsense-controller",
        "sku": "GAM-004",
        "name": "Sony DualSense Wireless Controller",
        "description": "PS5's signature controller with haptic feedback and adaptive triggers that adjust resistance in real time.",
        "category": "gaming",
        "price": 5990,
        "currency": "INR",
        "inventory": 30,
        "attributes": {
            "connectivity": "Bluetooth / USB-C", "compatibility": "PS5", "battery": "12 hours",
            "features": "Haptic feedback, adaptive triggers",
        },
        "image_url": "/products/placeholders/gaming.svg",
        "hero_image_url": "/products/placeholders/gaming.svg",
    },
    {
        "id": "microsoft-xbox-wireless-controller",
        "sku": "GAM-005",
        "name": "Microsoft Xbox Wireless Controller",
        "description": "Comfortable, reliable Xbox controller with a hybrid D-pad, compatible with both console and Windows PC.",
        "category": "gaming",
        "price": 5490,
        "currency": "INR",
        "inventory": 28,
        "attributes": {
            "connectivity": "Bluetooth / USB-C", "compatibility": "Xbox Series, PC", "battery": "40 hours (AA)",
            "features": "Hybrid D-pad",
        },
        "image_url": "/products/placeholders/gaming.svg",
        "hero_image_url": "/products/placeholders/gaming.svg",
    },
    {
        "id": "steam-deck-oled",
        "sku": "GAM-006",
        "name": "Valve Steam Deck OLED",
        "description": "Handheld gaming PC with a vivid OLED display, running the full Steam PC library on the go.",
        "category": "gaming",
        "price": 52999,
        "currency": "INR",
        "inventory": 4,
        "attributes": {
            "storage": "512GB SSD", "platform": "SteamOS", "connectivity": "Wi-Fi 6E, Bluetooth 5.3",
            "compatibility": "Steam PC library",
        },
        "image_url": "/products/placeholders/gaming.svg",
        "hero_image_url": "/products/placeholders/gaming.svg",
    },

    # ─── Smart Home (8 new) ─────────────────────────────────────
    {
        "id": "amazon-echo-dot-5th-gen",
        "sku": "SHM-001",
        "name": "Amazon Echo Dot (5th Gen)",
        "description": "Compact smart speaker with Alexa built in, ideal as an entry point into a smart home setup.",
        "category": "smart-home",
        "price": 4499,
        "currency": "INR",
        "inventory": 35,
        "attributes": {
            "connectivity": "Wi-Fi, Bluetooth", "voice_assistant": "Alexa",
            "power": "USB-C", "app_control": "Alexa App",
        },
        "image_url": "/products/placeholders/smart-home.svg",
        "hero_image_url": "/products/placeholders/smart-home.svg",
    },
    {
        "id": "google-nest-mini",
        "sku": "SHM-002",
        "name": "Google Nest Mini",
        "description": "Small smart speaker with Google Assistant, built to control smart home devices and answer questions hands-free.",
        "category": "smart-home",
        "price": 4999,
        "currency": "INR",
        "inventory": 30,
        "attributes": {
            "connectivity": "Wi-Fi, Bluetooth", "voice_assistant": "Google Assistant",
            "power": "USB-C", "app_control": "Google Home App",
        },
        "image_url": "/products/placeholders/smart-home.svg",
        "hero_image_url": "/products/placeholders/smart-home.svg",
    },
    {
        "id": "tp-link-tapo-smart-plug",
        "sku": "SHM-003",
        "name": "TP-Link Tapo P100 Smart Plug",
        "description": "Wi-Fi smart plug that turns any appliance into a schedulable, voice-controllable smart device.",
        "category": "smart-home",
        "price": 899,
        "currency": "INR",
        "inventory": 60,
        "attributes": {
            "connectivity": "Wi-Fi", "voice_assistant": "Alexa & Google Assistant",
            "power": "10A", "app_control": "Tapo App",
        },
        "image_url": "/products/placeholders/smart-home.svg",
        "hero_image_url": "/products/placeholders/smart-home.svg",
    },
    {
        "id": "philips-hue-smart-bulb",
        "sku": "SHM-004",
        "name": "Philips Hue White & Color Bulb",
        "description": "Millions-of-colors smart bulb with scheduling and scene support, the category benchmark for smart lighting.",
        "category": "smart-home",
        "price": 1999,
        "currency": "INR",
        "inventory": 40,
        "attributes": {
            "connectivity": "Zigbee (Hue Bridge)", "voice_assistant": "Alexa & Google Assistant",
            "power": "9W", "app_control": "Hue App",
        },
        "image_url": "/products/placeholders/smart-home.svg",
        "hero_image_url": "/products/placeholders/smart-home.svg",
    },
    {
        "id": "mi-smart-security-camera",
        "sku": "SHM-005",
        "name": "Mi Smart Camera 360°",
        "description": "Affordable 1080p home security camera with 360-degree pan, motion alerts, and night vision.",
        "category": "smart-home",
        "price": 2299,
        "currency": "INR",
        "inventory": 32,
        "attributes": {
            "connectivity": "Wi-Fi", "resolution": "1080p", "voice_assistant": "Google Assistant",
            "app_control": "Mi Home App", "night_vision": "Yes",
        },
        "image_url": "/products/placeholders/smart-home.svg",
        "hero_image_url": "/products/placeholders/smart-home.svg",
    },
    {
        "id": "tp-link-tapo-c210",
        "sku": "SHM-006",
        "name": "TP-Link Tapo C210",
        "description": "2K QHD home security camera with pan/tilt tracking and two-way audio for checking in from anywhere.",
        "category": "smart-home",
        "price": 2799,
        "currency": "INR",
        "inventory": 25,
        "attributes": {
            "connectivity": "Wi-Fi", "resolution": "2K QHD", "voice_assistant": "Alexa & Google Assistant",
            "app_control": "Tapo App", "night_vision": "Yes",
        },
        "image_url": "/products/placeholders/smart-home.svg",
        "hero_image_url": "/products/placeholders/smart-home.svg",
    },
    {
        "id": "eufy-robovac-11s",
        "sku": "SHM-007",
        "name": "Eufy RoboVac 11S",
        "description": "Slim, quiet robot vacuum with strong 1300Pa suction, designed to slide easily under furniture.",
        "category": "smart-home",
        "price": 15999,
        "currency": "INR",
        "inventory": 10,
        "attributes": {
            "connectivity": "N/A", "voice_assistant": "No", "power": "Rechargeable",
            "app_control": "Remote Control", "suction": "1300Pa",
        },
        "image_url": "/products/placeholders/smart-home.svg",
        "hero_image_url": "/products/placeholders/smart-home.svg",
    },
    {
        "id": "xiaomi-robot-vacuum-mop-2",
        "sku": "SHM-008",
        "name": "Xiaomi Robot Vacuum-Mop 2",
        "description": "Wi-Fi connected robot vacuum with mopping support and strong 4000Pa suction, controllable via app or voice.",
        "category": "smart-home",
        "price": 24999,
        "currency": "INR",
        "inventory": 8,
        "attributes": {
            "connectivity": "Wi-Fi", "voice_assistant": "Google Assistant", "power": "Rechargeable",
            "app_control": "Mi Home App", "suction": "4000Pa",
        },
        "image_url": "/products/placeholders/smart-home.svg",
        "hero_image_url": "/products/placeholders/smart-home.svg",
    },
]


def seed():
    """Seed the database. Drops existing data and re-seeds."""
    # Create all tables
    Base.metadata.create_all(bind=engine)

    db = SessionLocal()
    try:
        # Clear existing data (in reverse FK order)
        from app.models.order import Order, OrderItem
        db.query(OrderItem).delete()
        db.query(Order).delete()
        db.query(Product).delete()
        db.query(CommercePolicy).delete()
        db.query(Merchant).delete()
        db.commit()

        # Seed merchant
        merchant = Merchant(
            id=MERCHANT_ID,
            name="AgentCart Demo Merchant",
            currency="INR",
        )
        db.add(merchant)
        db.flush()

        # Seed products
        for p in PRODUCTS:
            product = Product(
                id=p["id"],
                merchant_id=MERCHANT_ID,
                sku=p["sku"],
                name=p["name"],
                description=p["description"],
                category=p["category"],
                price=p["price"],
                currency=p["currency"],
                inventory=p["inventory"],
                active=True,
                attributes=p.get("attributes"),
                image_url=p.get("image_url", ""),
                hero_image_url=p.get("hero_image_url", ""),
            )
            db.add(product)

        # Seed commerce policy
        policy = CommercePolicy(
            merchant_id=MERCHANT_ID,
            max_order_amount=70000,
            max_discount_percent=10,
            require_confirmation_above=25000,
            allowed_currency="INR",
            active=True,
        )
        db.add(policy)

        db.commit()
        print(f"[OK] Seeded merchant: {merchant.name}")
        print(f"[OK] Seeded {len(PRODUCTS)} products")
        print(f"[OK] Seeded commerce policy (max order: {policy.max_order_amount:,} INR)")
        print("\nDone!")

    except Exception as e:
        db.rollback()
        print(f"[ERROR] Seeding failed: {e}")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    seed()
